import Head from 'next/head';
import Image from 'next/image';
import Sidebar from '../components/Sidebar';
import Main from '../components/Main';

export default function Home() {

  const user = JSON.parse(localStorage.getItem("CurrentUser"));

  return (
    <div>
      <Head>
        <title>Whatsapp 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='flex'>
        <Sidebar username={user.username} email={user.email}/>
        <Main />
      </div>
      
      
    </div>
  )
}
